version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres-container
    ports:
      - "5433:${POSTGRES_PORT}"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
