name: Release

on:
  push:
    branches: ["master"]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git User
        uses: git-actions/set-user@v1

      - name: Read .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Set up .env for tests
        run: cp .env.template .env

      - name: Run Release
        run: npm run release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_Token }}

      - name: End message
        run: echo "All done!"
